Pm5
NgLam2911/InvCraft pull request #32
Opened 2023-09-07 07:28 UTC by GabBiswajit

2023-09-07 08:49 UTC, GabBiswajit commented
Hey @NgLam2911 if you free than check the Plugin...

2023-09-13 13:43 UTC, NgLam2911 requested changes
Everything is really good, theres is something left to clean up. Btw thanks for your PR and sorry because its was take a quite long time since i'm dont have much free time...

2023-09-13 13:43 UTC, NgLam2911 commented on src/NgLamVN/InvCraft/menu/CraftMenu.php
> +		$this->setResult($air);
this can be simplify as `$this->setResult(VanillaItems::AIR());`

2023-09-13 13:43 UTC, NgLam2911 commented on src/NgLamVN/InvCraft/menu/CraftMenu.php
> +				$this->menu->getInventory()->setItem($i,$air);
yes... as u was did ... use `VanillaItems::AIR()` instead

2023-09-13 13:49 UTC, GabBiswajit commented
@NgLam2911 now all good ?

2023-09-14 01:18 UTC, NgLam2911 commented
Requested changes wasnt resolved...

2023-09-14 03:42 UTC, closed without merging